version: '3.8'

services:
  db:
    image: postgres:16
    container_name: aptsim-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aptsim
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aptsim-network

  # You can add additional services here later if needed (e.g., backend API)

networks:
  aptsim-network:
    driver: bridge

volumes:
  postgres_data: